[package]
name = "MinimalCompressor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
rfd = "0.15"
tokio = { version = "1", features = ["rt", "macros", "time", "process"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3